var answers = [
    {
      id: 1,
      correct: [2],
      lo: "FL-1.1.1",
      kLevel: "K1",
      points: 1,
    },
    {
      id: 2,
      correct: [0],
      lo: "FL-1.2.1",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 3,
      correct: [0],
      lo: "FL-1.3.1",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 4,
      correct: [1],
      lo: "FL-1.4.1",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 5,
      correct: [1],
      lo: "FL-1.4.2",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 6,
      correct: [0, 4],
      lo: "FL-1.4.5",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 7,
      correct: [1],
      lo: "FL-1.5.1",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 8,
      correct: [3],
      lo: "FL-1.5.2",
      kLevel: "K1",
      points: 1,
    },
    {
      id: 9,
      correct: [3],
      lo: "FL-2.1.2",
      kLevel: "K1",
      points: 1,
    },
    {
      id: 10,
      correct: [2],
      lo: "FL-2.1.3",
      kLevel: "K1",
      points: 1,
    },
    {
      id: 11,
      correct: [3],
      lo: "FL-2.1.5",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 12,
      correct: [2],
      lo: "FL-2.1.6",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 13,
      correct: [0],
      lo: "FL-2.2.1",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 14,
      correct: [1],
      lo: "FL-2.2.3",
      kLevel: "K2",
      points: 1,
    },
    {
      id: 15,
      correct: [0],
      lo: "FL-3.1.2",
      kLevel: "K2",
      points: 1,
    },
  ];
